name: Snyk Ruby Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0 # Adjust based on your project's Ruby version

      # Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Install Snyk
      - name: Install Snyk
        run: npm install -g snyk

      # Authenticate Snyk
      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      # Run Snyk scan
      - name: Run Snyk Test
        run: snyk test --all-projects
