name: Trivy CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget -y
          wget -qO- https://github.com/aquasecurity/trivy/releases/latest/download/trivy_$(uname -s)_$(uname -m).tar.gz | sudo tar zx -C /usr/local/bin/

      # Step 3: Run Trivy Scan on Filesystem
      - name: Trivy Filesystem Scan
        run: |
          trivy fs --exit-code 0 --severity CRITICAL,HIGH --output trivy-report.txt .
        
      # Step 4: Run Trivy Scan on Container Image (Optional)
      - name: Trivy Container Image Scan
        run: |
          trivy image --exit-code 0 --severity CRITICAL,HIGH --output trivy-image-report.txt <image-name>

      # Step 5: Upload Reports
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.txt
