name: Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Install Trivy
      - name: Install Trivy
        run: |
          VERSION=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep tag_name | cut -d '"' -f 4)
          wget https://github.com/aquasecurity/trivy/releases/download/${VERSION}/trivy_$(uname -s)_$(uname -m).tar.gz
          tar zxvf trivy_$(uname -s)_$(uname -m).tar.gz
          sudo mv trivy /usr/local/bin/

      # Step 3: Run a scan on the repository
      - name: Run Trivy File System Scan
        run: trivy fs . --exit-code 1 --severity HIGH,CRITICAL

      # Step 4: Upload the scan results
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy.log
