name: Trivy Ruby Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Install Ruby and Bundler
      - name: Install Ruby and Bundler
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full
          sudo gem install bundler

      # Step 3: Install dependencies (optional, but ensures lock file is generated)
      - name: Install dependencies (bundle install)
        run: bundle install

      # Step 4: Install Trivy
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      # Step 5: Run Trivy Scan
      - name: Run Trivy Scan
        run: |
          trivy fs . --exit-code 1 --severity HIGH,CRITICAL

      # Step 6: Upload Trivy Report
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy.log
